version: '3.8'
services:
  backend:
    build: .
    ports:
      -  "9876:9876"
  frontend:
    image: nginx:mainline-alpine
    ports:
      - "9875:80"
    command: >
      sh -c "apk add git &&
              mkdir -p /app &&
              cd /app &&
              git clone https://github.com/MV-Alhambra/Webclient &&
              cp -r  Webclient/src/* /usr/share/nginx/html &&
              echo Surf to http://localhost:9875/ &&
              nginx -g 'daemon off;'
             " 

